name: Java CI con Gradle

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configurar Java
      uses: actions/setup-java@v2
      with:
        java-version: '17' # Actualizado a Java 17
        distribution: 'adopt'

    - name: Ejecutar pruebas con Gradle
      run: |
        pwd
        cd apiTestAutomation/swaggerPetstore
        pwd
        sudo chmod -R 777 $(pwd)
        ./gradlew cleanTest test

    - name: Caché de dependencias de Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
