name: Java CI con Gradle y Docker

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Pull Docker Image
      run: |
        docker pull swaggerapi/petstore3:unstable

    - name: Iniciar Contenedor Docker
      run: |
        docker run --name swaggerapi-petstore3 -d -p 8080:8080 swaggerapi/petstore3:unstable

    - name: Esperar a que el servicio esté disponible
      run: |
        wget --waitretry=5 --retry-connrefused -T 15 -O- http://localhost:8080/api/v3/openapi.json

    - name: Caché de dependencias de Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Ejecutar pruebas con Gradle
      run: |
        cd apiTestAutomation/swaggerPetstore
        sudo chmod -R 777 $(pwd)
        ./gradlew clean build -x test
        ./gradlew test --tests *runners* aggregate -i

    - name: Recoger Evidencias de Pruebas
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: |
          apiTestAutomation/swaggerPetstore/target/site/**
